# This workflow automates the validation of (new) bug reports.
# It handles two main flows: new issues and edited issues.
#
# 1. New Issue:
# - Parse the issue based on the provided template.
# - Verify the data in the template fields.
# - If there are issues with the data:
#   - Notify the issue creator via a comment, listing the items that need to be fixed.
#   - Inform the creator that the issue will be discarded if not corrected.
# - If the data is correct:
#   - Apply the appropriate tags to the issue.
#   - Thank the user for their contribution.
#
# 2. Edited Issue:
# - Re-validate the issue after the user has made corrections.
# - Follow the same steps as the new issue flow.
# - Reuse the existing comment to provide further instructions or confirmation.

name: Bug Report Validation
on:
  issues:
    types: [opened, edited]

jobs:
  validate-new-report:
    if: ${{ github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'bug:new') }}
    name: Validate a new bug report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse issue form
        uses: Ansuel/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug-report.yml
          
      - name: Validate Release
        uses: ./.github/actions/validate-release
        id: validate-release
        with:
          release: ${{ steps.issue-parser.outputs.issueparser_release }}

      # Checkout release tag
      # Validate revision
      # Validate target & subtarget
      # Validate device

      # Communicate with user
      # Update labels

  validate-updated-report:
    if: ${{ github.event.action == 'edited' && contains(github.event.issue.labels.*.name, 'bug:invalid') }}
    name: Re-validate an updated bug report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Placeholder step
        run: echo "This is a placeholder for your custom steps."
